#!/usr/bin/env python3
"""
Test script to verify that feasible combinations generated by the UCSB environment
are correct and match the actual network topology.
"""

import sys
import os
sys.path.append(os.path.join(os.path.dirname(__file__), '..'))

import numpy as np
import networkx as nx
from src.environments.ucsb_meshnet_memmap import UCSBMeshnetMemmapEnvironment

def verify_feasible_combinations(env, round_idx, verbose=True):
    """
    Verify that feasible combinations are correct for a given round.
    
    Args:
        env: UCSB environment instance
        round_idx: Round index to verify
        verbose: Whether to print detailed information
        
    Returns:
        dict: Verification results
    """
    if verbose:
        print(f"\n=== Verifying Round {round_idx} ===")
    
    # Get available arms and feasible combinations from environment
    available_arms = env.get_available_arms_for_round(round_idx)
    feasible_combinations = env.get_feasible_combinations(set(available_arms))
    
    if verbose:
        print(f"Available arms: {len(available_arms)}")
        print(f"Feasible combinations: {len(feasible_combinations)}")
    
    # Build the actual network graph for this round
    adj_matrix = env.get_available_links_for_round(round_idx)
    G = nx.DiGraph()
    
    # Add nodes
    for i, node in enumerate(env.nodes):
        G.add_node(node)
    
    # Add edges based on adjacency matrix
    for i, u in enumerate(env.nodes):
        for j, v in enumerate(env.nodes):
            if adj_matrix[i, j]:
                G.add_edge(u, v)
    
    if verbose:
        print(f"Network nodes: {len(G.nodes())}")
        print(f"Network edges: {len(G.edges())}")
    
    # Verify each feasible combination
    verification_results = {
        'round_idx': round_idx,
        'available_arms': len(available_arms),
        'feasible_combinations': len(feasible_combinations),
        'valid_combinations': 0,
        'invalid_combinations': 0,
        'errors': []
    }
    
    for combo_idx, combination in enumerate(feasible_combinations):
        if verbose:
            print(f"\n  Checking combination {combo_idx + 1}: {combination}")
        
        # Convert arm indices to actual links
        combo_links = []
        for arm in combination:
            if arm < len(env.arms):
                combo_links.append(env.arm_to_link[arm])
            else:
                error_msg = f"Invalid arm index {arm} (max: {len(env.arms) - 1})"
                verification_results['errors'].append(error_msg)
                if verbose:
                    print(f"    ERROR: {error_msg}")
                continue
        
        if verbose:
            print(f"    Links: {combo_links}")
        
        # Check if all links exist in the network
        all_links_exist = True
        for u, v in combo_links:
            if not G.has_edge(u, v):
                error_msg = f"Link {u} -> {v} does not exist in network"
                verification_results['errors'].append(error_msg)
                all_links_exist = False
                if verbose:
                    print(f"    ERROR: {error_msg}")
        
        if not all_links_exist:
            verification_results['invalid_combinations'] += 1
            continue
        
        # Check if the combination forms a valid path from source to destination
        try:
            # Reconstruct path from links
            path = reconstruct_path_from_links(combo_links, env.source, env.destination)
            
            if path is None:
                error_msg = f"Combination does not form a valid path from {env.source} to {env.destination}"
                verification_results['errors'].append(error_msg)
                verification_results['invalid_combinations'] += 1
                if verbose:
                    print(f"    ERROR: {error_msg}")
                continue
            
            # Verify path exists in the network
            if not nx.has_path(G, env.source, env.destination):
                error_msg = f"No path exists from {env.source} to {env.destination} in network"
                verification_results['errors'].append(error_msg)
                verification_results['invalid_combinations'] += 1
                if verbose:
                    print(f"    ERROR: {error_msg}")
                continue
            
            # Check if reconstructed path matches a valid path in the network
            try:
                network_path = nx.shortest_path(G, env.source, env.destination)
                if verbose:
                    print(f"    Reconstructed path: {path}")
                    print(f"    Network shortest path: {network_path}")
                    print(f"    Path length: {len(path) - 1} hops")
                    print(f"    ✓ VALID")
            except nx.NetworkXNoPath:
                error_msg = f"No path exists in network from {env.source} to {env.destination}"
                verification_results['errors'].append(error_msg)
                verification_results['invalid_combinations'] += 1
                if verbose:
                    print(f"    ERROR: {error_msg}")
                continue
            
            verification_results['valid_combinations'] += 1
            
        except Exception as e:
            error_msg = f"Error reconstructing path: {str(e)}"
            verification_results['errors'].append(error_msg)
            verification_results['invalid_combinations'] += 1
            if verbose:
                print(f"    ERROR: {error_msg}")
    
    if verbose:
        print(f"\n  Summary: {verification_results['valid_combinations']} valid, "
              f"{verification_results['invalid_combinations']} invalid")
    
    return verification_results

def reconstruct_path_from_links(links, source, destination):
    """
    Reconstruct a path from a list of links.
    
    Args:
        links: List of (u, v) tuples representing links
        source: Source node
        destination: Destination node
        
    Returns:
        list: Path as list of nodes, or None if invalid
    """
    if not links:
        return None
    
    # Create a graph from the links
    G = nx.DiGraph()
    for u, v in links:
        G.add_edge(u, v)
    
    # Check if path exists
    try:
        path = nx.shortest_path(G, source, destination)
        return path
    except nx.NetworkXNoPath:
        return None

def test_feasible_set_verification():
    """Main test function to verify feasible combinations across multiple rounds."""
    
    # Get the largest dataset folder
    data_dir = "data/ucsb/1144393236-1144450070"
    neighbortable_files = []
    for f in os.listdir(data_dir):
        if f.startswith("neighbortable-"):
            neighbortable_files.append(os.path.join(data_dir, f))
    neighbortable_files.sort()
    
    print(f"Found {len(neighbortable_files)} neighbortable files")
    
    # Use the best node pair we found earlier
    source = "10.1.1.109"
    destination = "10.1.1.5"
    
    # Create environment with different configurations
    test_configs = [
        {
            "name": "Conservative",
            "max_feasible_combinations": 10,
            "max_path_length": 3,
            "max_paths_per_algorithm": 5
        },
        {
            "name": "Default",
            "max_feasible_combinations": 50,
            "max_path_length": 8,
            "max_paths_per_algorithm": 25
        }
    ]
    
    for config in test_configs:
        print(f"\n{'='*80}")
        print(f"Testing Configuration: {config['name']}")
        print(f"  max_feasible_combinations: {config['max_feasible_combinations']}")
        print(f"  max_path_length: {config['max_path_length']}")
        print(f"  max_paths_per_algorithm: {config['max_paths_per_algorithm']}")
        
        # Create environment
        env = UCSBMeshnetMemmapEnvironment(
            neighbortable_files=neighbortable_files[:20],  # Use first 20 files
            routes_per_minute=4,
            source=source,
            destination=destination,
            max_feasible_combinations=config['max_feasible_combinations'],
            max_path_length=config['max_path_length'],
            max_paths_per_algorithm=config['max_paths_per_algorithm']
        )
        
        # Test multiple rounds
        total_valid = 0
        total_invalid = 0
        total_combinations = 0
        all_errors = []
        
        for round_idx in range(min(10, env.num_rounds)):  # Test first 10 rounds
            result = verify_feasible_combinations(env, round_idx, verbose=False)
            
            total_valid += result['valid_combinations']
            total_invalid += result['invalid_combinations']
            total_combinations += result['feasible_combinations']
            all_errors.extend(result['errors'])
            
            print(f"  Round {round_idx}: {result['valid_combinations']} valid, "
                  f"{result['invalid_combinations']} invalid, "
                  f"{result['feasible_combinations']} total")
        
        # Print summary
        print(f"\n  SUMMARY for {config['name']}:")
        print(f"    Total combinations: {total_combinations}")
        print(f"    Valid combinations: {total_valid}")
        print(f"    Invalid combinations: {total_invalid}")
        print(f"    Success rate: {total_valid/max(1, total_combinations)*100:.1f}%")
        
        if all_errors:
            print(f"    Errors found: {len(all_errors)}")
            for error in all_errors[:5]:  # Show first 5 errors
                print(f"      - {error}")
            if len(all_errors) > 5:
                print(f"      ... and {len(all_errors) - 5} more errors")
        else:
            print(f"    ✓ No errors found!")
        
        env.cleanup()
    
    print(f"\n{'='*80}")
    print("Verification completed!")

if __name__ == "__main__":
    test_feasible_set_verification() 