#!/usr/bin/env python3
"""
Test Environment Feasible Paths Accuracy
========================================

This script tests whether the UCSB environment correctly generates
feasible paths each round, especially for the node pair 10.1.1.102 -> 10.1.1.25.
"""

import os
import sys
import glob
import numpy as np
import networkx as nx
from typing import List, Set, Tuple

# Add project root to Python path
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from src.environments.ucsb_meshnet_memmap import UCSBMeshnetMemmapEnvironment

def parse_neighbortable_file(file_path: str) -> Tuple[Set[str], List[Tuple[str, str]]]:
    """Parse a neighbortable file to extract nodes and edges."""
    nodes = set()
    edges = []
    
    try:
        with open(file_path, 'r') as f:
            for line in f:
                line = line.strip()
                if line and not line.startswith('#'):
                    parts = line.split()
                    if len(parts) >= 2:
                        node = parts[0]
                        neighbor = parts[1]
                        nodes.add(node)
                        nodes.add(neighbor)
                        edges.append((node, neighbor))
    except Exception as e:
        print(f"Error parsing {file_path}: {e}")
    
    return nodes, edges

def verify_environment_paths():
    """Verify the feasible paths generated by the environment."""
    print("Testing Environment Feasible Paths Accuracy")
    print("=" * 80)
    
    # Setup environment parameters
    data_dir = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), 'data', 'ucsb')
    period1_dir = os.path.join(data_dir, '1143927049-1143953729')
    
    # Get trace files
    neighbortable_files = glob.glob(os.path.join(period1_dir, 'neighbortable-*'))
    neighbortable_files = sorted(neighbortable_files)
    
    print(f"Found {len(neighbortable_files)} trace files")
    
    # Test node pair
    src = '10.1.1.102'
    dst = '10.1.1.25'
    
    print(f"Testing node pair: {src} -> {dst}")
    print(f"Using first 20 trace files for verification")
    
    # Test first 20 files
    test_files = neighbortable_files[:20]
    
    # Create environment
    env = UCSBMeshnetMemmapEnvironment(
        neighbortable_files=test_files,
        source=src,
        destination=dst,
        routes_per_minute=4,
        max_path_length=3,
        max_paths_per_algorithm=25,
        seed=42
    )
    
    print(f"\nEnvironment created with {len(test_files)} trace files")
    print(f"Environment rounds: {env.num_rounds}")
    print(f"Routes per minute: {env.routes_per_minute}")
    
    # Test each round
    discrepancies = []
    
    for round_idx in range(min(20, env.num_rounds)):
        print(f"\n--- Round {round_idx} ---")
        
        # Get environment's feasible combinations
        available_arms = set(env.get_available_arms_for_round(round_idx))
        env_feasible = env.get_feasible_combinations(available_arms)
        env_path_count = len(env_feasible) if env_feasible else 0
        
        print(f"Environment feasible paths: {env_path_count}")
        print(f"Available arms: {len(available_arms)}")
        
        # Manually verify using the corresponding trace file
        if round_idx < len(test_files):
            trace_file = test_files[round_idx]
            filename = os.path.basename(trace_file)
            
            # Parse trace file manually
            nodes, edges = parse_neighbortable_file(trace_file)
            
            # Build graph
            G = nx.Graph()
            G.add_nodes_from(nodes)
            G.add_edges_from(edges)
            
            # Check connectivity manually
            if src in G and dst in G and nx.has_path(G, src, dst):
                # Find all simple paths up to 3 hops
                all_paths = list(nx.all_simple_paths(G, src, dst, cutoff=3))
                manual_path_count = len(all_paths)
                
                print(f"Manual verification ({filename}): {manual_path_count} paths")
                
                if manual_path_count >= 2:
                    print(f"  Paths: {all_paths}")
                
                # Check for discrepancy
                if env_path_count != manual_path_count:
                    discrepancy = {
                        'round': round_idx,
                        'filename': filename,
                        'env_paths': env_path_count,
                        'manual_paths': manual_path_count,
                        'env_feasible': env_feasible,
                        'manual_paths_detail': all_paths
                    }
                    discrepancies.append(discrepancy)
                    print(f"  ⚠️  DISCREPANCY FOUND!")
                else:
                    print(f"  ✓ Path counts match")
            else:
                print(f"Manual verification ({filename}): No path found")
                if env_path_count > 0:
                    discrepancy = {
                        'round': round_idx,
                        'filename': filename,
                        'env_paths': env_path_count,
                        'manual_paths': 0,
                        'env_feasible': env_feasible,
                        'manual_paths_detail': []
                    }
                    discrepancies.append(discrepancy)
                    print(f"  ⚠️  DISCREPANCY FOUND!")
                else:
                    print(f"  ✓ No paths (both agree)")
    
    # Summary
    print(f"\n{'='*80}")
    print("SUMMARY")
    print(f"{'='*80}")
    print(f"Total rounds tested: {min(20, env.num_rounds)}")
    print(f"Discrepancies found: {len(discrepancies)}")
    
    if discrepancies:
        print(f"\nDiscrepancies:")
        for disc in discrepancies:
            print(f"  Round {disc['round']} ({disc['filename']}):")
            print(f"    Environment: {disc['env_paths']} paths")
            print(f"    Manual: {disc['manual_paths']} paths")
            if disc['env_feasible']:
                print(f"    Environment paths: {disc['env_feasible']}")
            if disc['manual_paths_detail']:
                print(f"    Manual paths: {disc['manual_paths_detail']}")
    else:
        print(f"✓ All path counts match between environment and manual verification")

def test_algorithm_performance():
    """Test algorithm performance with the verified node pair."""
    print(f"\n{'='*80}")
    print("TESTING ALGORITHM PERFORMANCE")
    print(f"{'='*80}")
    
    # Setup environment
    data_dir = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), 'data', 'ucsb')
    period1_dir = os.path.join(data_dir, '1143927049-1143953729')
    neighbortable_files = glob.glob(os.path.join(period1_dir, 'neighbortable-*'))
    neighbortable_files = sorted(neighbortable_files)
    
    src = '10.1.1.102'
    dst = '10.1.1.25'
    
    # Create environment with more files for longer test
    test_files = neighbortable_files[:50]  # Use 50 files
    
    env = UCSBMeshnetMemmapEnvironment(
        neighbortable_files=test_files,
        source=src,
        destination=dst,
        routes_per_minute=4,
        max_path_length=3,
        max_paths_per_algorithm=25,
        seed=42
    )
    
    print(f"Environment created with {len(test_files)} files")
    print(f"Environment rounds: {env.num_rounds}")
    
    # Test a few rounds to see path availability
    path_availability = []
    for round_idx in range(min(100, env.num_rounds)):
        feasible = env.get_feasible_combinations(round_idx)
        path_count = len(feasible) if feasible else 0
        path_availability.append(path_count)
        
        if round_idx < 10:  # Show first 10 rounds
            print(f"Round {round_idx}: {path_count} feasible paths")
    
    # Statistics
    total_rounds = len(path_availability)
    rounds_with_paths = sum(1 for count in path_availability if count > 0)
    rounds_with_multiple = sum(1 for count in path_availability if count >= 2)
    
    print(f"\nPath Availability Statistics:")
    print(f"  Total rounds: {total_rounds}")
    print(f"  Rounds with any paths: {rounds_with_paths} ({rounds_with_paths/total_rounds*100:.1f}%)")
    print(f"  Rounds with multiple paths: {rounds_with_multiple} ({rounds_with_multiple/total_rounds*100:.1f}%)")
    
    if rounds_with_multiple > 0:
        print(f"  This explains why algorithms might show different performance")
    else:
        print(f"  ⚠️  No rounds with multiple paths - all algorithms should perform similarly!")

def main():
    """Main function."""
    verify_environment_paths()
    test_algorithm_performance()

if __name__ == "__main__":
    main() 